name=AUI
version=0.3.80
author=Amber-Sophia Schröck
maintainer=Amber-Sophia Schröck <ambersophia.schroeck@gmail.com>
sentence=Deterministic event-driven embedded framework for Arduino.
paragraph=AUI provides a modular message-bus architecture for hardware elements such as buttons, LEDs, sensors, buses, and timers. Inspired by UI design patterns, but built for real hardware: no loop(), no dynamic allocation, fully reproducible state machines.
category=Other
url=https://github.com/RoseLeDark/arduino-aui
architectures=*
