name=AUI
version=0.3.13
author=Amber-Sophia Schröck
maintainer=Amber-Sophia Schröck <ambersophia.schroeck@gmail.com>
sentence=Deterministic event-driven hardware framework for Arduino.
paragraph=AUI provides a modular message-based architecture for embedded systems without relying on the Arduino loop() model.
category=Other
url=https://github.com/RoseLeDark/arduino-aui
architectures=*
